### ISSUE TITLE
How to run this from a cloud function?

### ISSUE THREAD

**Issue by 0x80** [Johannes-Berggren/firestore-to-bigquery-export#6]
Hi,

I would like to schedule the bigquery data import using a cloud scheduler triggering a cloud function.

The problem is that your library (and other solutions I've encountered) require me to specify service credentials. I do not know how to access the credentials that Google uses when running the cloud function.

I could attach the credentials to the runtime myself as part of a functions.config secret, but that seems like a very odd thing to do.

Do you have an idea how to approach this?

**Comment by Johannes-Berggren** [comment]
Hi @0x80 !

That's what I'm doing too :-)

This is a good question - I should update the package in order to make it work using the default credentials provided by the Cloud Function environment.

But in the meantime, what you need to do is go to the GCP Console -> IAM & Admin -> Service Accounts, and create a new service account (or use one of your existing ones) with permissions to write to BigQuery, and to read from Firestore.

Then you generate a key for that account, which will let you download the service account file in question :-)

It can be very handy to be able to specify in your code that you want to for example export data to a dev environment in a different GCP-project. That's why a service account file is currently required.

Hope this helps!

J

**Comment by 0x80** [comment]
Never mind. I found a way to get the credentials using the googleapis library.

This also allows me to schedule bigquery imports directly from firestore export files, via the REST API, so I prefer to do that. 

Here's the code to get credentials in case it's useful to someone:

```ts
import { google } from "googleapis";
import { OAuth2Client } from "google-auth-library";
import { db } from "../firebase-admin-client";
import { Storage } from "@google-cloud/storage";

export async function getGoogleApiAuthentication(): Promise<{
  projectId: string;
  credential: OAuth2Client;
}> {
  const auth = new google.auth.GoogleAuth({
    // Scopes can be specified either as an array or as a single, space-delimited string.
    scopes: ["https://www.googleapis.com/auth/cloud-platform"]
  });

  const { projectId, credential } = await auth.getApplicationDefault();

  if (!projectId) {
    throw new Error(
      `Missing projectId from auth.getApplicationDefault() response`
    );
  }

  return { projectId, credential };
}
```

**Comment by Johannes-Berggren** [comment]
Awesome, thanks for sharing @0x80 !
